// <auto-generated />
using DomainPractice;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DomainPractice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoverageDataInvestmentData", b =>
                {
                    b.Property<long>("CoveragesId")
                        .HasColumnType("bigint");

                    b.Property<long>("InvestmentsId")
                        .HasColumnType("bigint");

                    b.HasKey("CoveragesId", "InvestmentsId");

                    b.HasIndex("InvestmentsId");

                    b.ToTable("InvestmentCoverages");
                });

            modelBuilder.Entity("DomainPractice.Coverage.CoverageData", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MaximumAllowedInvestment")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("MinimumAllowedInvestment")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("NetPercent")
                        .HasColumnType("decimal(10,9)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)");

                    b.HasKey("Id");

                    b.ToTable("Coverages");
                });

            modelBuilder.Entity("DomainPractice.Investment.InvestmentData", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.ToTable("Investments");
                });

            modelBuilder.Entity("CoverageDataInvestmentData", b =>
                {
                    b.HasOne("DomainPractice.Coverage.CoverageData", null)
                        .WithMany()
                        .HasForeignKey("CoveragesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainPractice.Investment.InvestmentData", null)
                        .WithMany()
                        .HasForeignKey("InvestmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
